apiVersion: tekton.dev/v1beta1
kind: task
metadata:
  name: kics-scan
spec:
  description: |
    Scans code for IaC related issus
  workspaces:
  - name: source
    description: |
      Volume to Scan
  steps:
  - name: scan
    image: checkmarx/kics:latest
    script: |
      kics scan -p $(workspaces.source.path) -o /vagrant/sarif-raport --report-formats sarif















