apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vulnerability-image-scanning
spec:
  pipelineRef:
    name: container-image-scan-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: image
    value: debian:latest