apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: container-image-scan-pipeline
spec:
  description: |
    This pipeline scan image.
  params:
  - name: image
    type: string
    description: The image to scan
  workspaces:
  - name: shared-data
    description: |
      This workspace contains scan results files, so they can be read by the
      next task.
  tasks:
  - name: scan-image
    taskRef:
      name: container-image-scan
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: image
      value: $(params.image)