apiVersion: tekton.dev/v1beta1
kind: task
metadata:
  name: checkov-scan
spec:
  description: |
    Scans code for IaC related issus
  workspaces:
  - name: source
    description: |
      Volume to Scan
    mountPath: /tf
  steps:
  - name: scan
    image: bridgecrew/checkov
    script: |
      checkov  --directory $(workspaces.source.path) -s --summary-position bottom -o sarif --output-file-path /checkov/sarif-raport
