apiVersion: tekton.dev/v1beta1
kind: task
metadata:
  name: container-image-scan
spec:
  description: |
    Scans image for security related issus
  workspaces:
  - name: source
    description: |
      workspaces for saving results
  params:
    - name: image
      description: Image to scan for vulnerabilities
    - name: version
      description: Version of Trivy scanner image
    - name: format
      description: Format to ouput report in
      default: sarif
    - name: report-name
      description: Name of report
      default: trivy-image-report
  steps:
  - name: image-scan
    image: aquasec/trivy:$(params.version)
    script: |
      trivy image $(params.image) --format $(params.format) -o $(params.report-name).$(params.format) 



